### ISSUE TITLE
Make pyspark dependency optional

### ISSUE THREAD

**Issue by Spriithy** [Kitware/bat#132]
Hi,

I'm using ZAT for its Zeek log file reading capabilities for pandas processing only on small controllers.

However, installations fails on these due to the extraneous 213MB of pyspark code dependency which we obviously don't need.

Could you please make it possible to install specific features of Zat independently ? I was thinking like

```
pip install zat # installs basic ZAT features, pandas interface etc
pip install zat[pyspark] # installs the pyspark functionnalities
pip install zat[all] # installs everything
```

Thanks in advance !

**Comment by brifordwylie** [comment]
@spriithy

Done...
The pypi 0.4.3 release now has pyspark as an optional dependency, used the proposed approach above. 👍

**Comment by Spriithy** [comment]
Wow thanks !

This is probably the fastest handling of ANY PR I ever submitted... by far...

Thank you so much for the work put in ZAT :)
