### ISSUE TITLE
Support for Intelligence Framework 

### ISSUE THREAD

**Issue by gorzilla** [Kitware/bat#133]
Would be great if zat could read/write the [intel format](https://docs.zeek.org/en/master/frameworks/intel.html#loading-intelligence) that Zeek uses. At the moment when I try to load a file like [this one](https://raw.githubusercontent.com/CriticalPathSecurity/Zeek-Intelligence-Feeds/master/cps-collected-iocs.intel), I get an error because there's no timestamp column.

`KeyError: "None of ['ts'] are in the columns"`

**Comment by brifordwylie** [comment]
Okay sounds like a good idea, I'll look into adding support for that.

**Comment by zmaasaoui** [comment]
I have the same issue. Any updates ?

**Comment by brifordwylie** [comment]
Oh yeah, I need to do this.. will try to squeeze it in today.

**Comment by brifordwylie** [comment]
@gorzilla @zmaasaoui just so I understand.... what's the use case that you're looking to support with zat? You want to read in the intel format as a pandas dataframe? Or do you want to read the resulting intel.log?

**Comment by brifordwylie** [comment]
Okay.. so I'm assuming the usecase is to read in the intel data with the intel format that @gorzilla linked. The patch was easy and I'll make a new PyPI distribution today.  Here's how you can test it out...

```
> python zeek_to_pandas.py ../data/intel_example.intel
Could not find ts/timestamp for index...
               indicator indicator_type meta.source meta.do_notice meta.desc
0      0-de-franchise.ca  Intel::DOMAIN     CPS-CTI              F   CIT0DAY
1  0-deductible-offer.ca  Intel::DOMAIN     CPS-CTI              F   CIT0DAY
2                 0-o.ca  Intel::DOMAIN     CPS-CTI              F   CIT0DAY
3             0059.co.kr  Intel::DOMAIN     CPS-CTI              F   CIT0DAY
4                 007.no  Intel::DOMAIN     CPS-CTI              F   CIT0DAY
```

**Comment by brifordwylie** [comment]
Okay a new version has been pushed to PyPI (0.4.4).. please let me know if it works for you guys.

**Comment by zmaasaoui** [comment]
Thank you @brifordwylie. It works for me.
