### ISSUE TITLE
Demo file has errors

### ISSUE THREAD

**Issue by DAYceng** [Kitware/bat#137]
Hi，I found an error while running the demo routine under the notebook folder
The error is in this file：[zat/notebooks/Anomaly_Detection.ipynb](https://github.com/SuperCowPowers/zat/blob/main/notebooks/Anomaly_Detection.ipynb)

at In[28]
`# Distribution of the request body length
Zeek_df[['request_body_len']].hist()
print('\nFor this small demo dataset almost all request_body_len are 0\nCluster 2 represents outliers')`
Among them, 'Zeek_df' should be changed to 'zeek_df', consistent with the previous definition, otherwise an error will be reported

**Comment by brifordwylie** [comment]
Ah, thanks. I've fixed the notebook and pushed to main branch
