### ISSUE TITLE
http.log file with the size of 2.0 MB zat stuck 

### ISSUE THREAD

**Issue by lokipython** [Kitware/bat#138]
I have a log file http.log file with the size of 2.0MB , my script just hang when i load it to data frames if i give small size file it loads 
![up11](https://user-images.githubusercontent.com/87889016/161219291-f0be4f71-56ab-4140-ace4-e448b18c86ce.png)
above image its not loading

![up44](https://user-images.githubusercontent.com/87889016/161219513-b00ea55c-8308-47fc-8698-dbe71a9b2432.png)
this one is loading because of size may be , any help so that i  can load large files

**Comment by brifordwylie** [comment]
@lokipython we have read in Zeek log files that are 2-3 Gigabytes (see https://supercowpowers.github.io/zat/large_dataframes.html) so there should not be any problem with a 2MB file, can you give a bit more information on the issue you're seeing. Also you can mail me the file at briford@supercowpowers.com if you'd like me to diagnose the issue.
