### ISSUE TITLE
Unable to run the code 

### ISSUE THREAD

**Issue by Bakloul1998** [Kitware/bat#139]
Can you help me to how to use and run the code ?

**Comment by brifordwylie** [comment]
@Bakloul1998 that's a pretty broad question. ZAT can be used in a bunch of different ways.. the documentation contains many code examples and notebooks: https://supercowpowers.github.io/zat/ please start with the examples page https://supercowpowers.github.io/zat/examples.html.  

Is there something specific that you've tried but didn't work?  Please provide the code that you're having issues with.

**Comment by Bakloul1998** [comment]
thank you for your reply ,
I am considering your repository which I see as very useful , beacause I am working on the machine learning side with Zeek so that Zeek can detect activities that are not normal.
Should the algorithm I'm going to build be separate and analyze zeek's logs as input or should it be integrated while Zeek analyzes the data flow through the network, which I see as impossible?
I don't know how to consider the concept of machine learning with the behavior of zeek .
Can you help me by suggesting ideas ?

**Comment by brifordwylie** [comment]
There's an Anomaly Detection notebook listed in the documentation that show use of Isolation Forests for anomaly detection. https://nbviewer.org/github/SuperCowPowers/zat/blob/main/notebooks/Anomaly_Detection.ipynb

I would start with some of the 'getting started' notebooks listed on the Repo Front Page Readme.. https://github.com/SuperCowPowers/zat like perhaps [Zeek to Scikit-Learn](https://nbviewer.jupyter.org/github/SuperCowPowers/zat/blob/main/notebooks/Zeek_to_Scikit_Learn.ipynb) notebook

So definitely reading stuff/trying stuff is encouraged....
