### ISSUE TITLE
Stuck when attempting to make a Pandas DF

### ISSUE THREAD

**Issue by jailenbailey** [Kitware/bat#140]
Hi there!

I am new to using ZAT and have encountered an issue when attempting to use either the zeek_log_reader or the LogToDataFrame functions. In Jupyter, it seemed as if my kernel was having an issue, because I couldn't use a print statement. However, when I moved over to using VSCode, I was able to see that the cell for the follwing was just getting stuck, as I let the cell get to 10 minutes before I interrupted:

log_to_df = LogToDataFrame()
http_df = log_to_df.create_dataframe('./Scenario1/conn.log')
http_df.head()

I was just wondering if this is an issue because of using Python 3.10.6, or if I may have done something incorrectly when installing?

**Comment by brifordwylie** [comment]
Hi @jailenbailey 

Thanks for the issue report. I've tried to replicate using Python 3.10.6 but it all seems to work fine. Here's the working code snippet.

```
pip install zat

❯ ipython
Python 3.10.6 
In [1]: from zat import log_to_dataframe
In [2]: log_to_df = log_to_dataframe.LogToDataFrame()
In [3]: conn_df = log_to_df.create_dataframe('conn.log')
In [4]: conn_df.head()
Out[4]:
                                              uid      id.orig_h  id.orig_p  ... resp_pkts  resp_ip_bytes tunnel_parents
ts                                                                           ...
2013-09-15 23:44:27.706265088  CoyZrY2g74UvMMgp4a  192.168.33.10       1032  ...        31          39641        (empty)
2013-09-15 23:44:28.093470208  CaJxA82D4HGxRzEgjc  192.168.33.10       1039  ...        13          15414        (empty)
2013-09-15 23:44:28.082700032  CLp0PF2EcdkpGemkW5  192.168.33.10       1036  ...        11           7292        (empty)
2013-09-15 23:44:28.082016000  CvNL1g1RGVeCAszIRj  192.168.33.10       1035  ...        13          10413        (empty)
2013-09-15 23:44:28.088450048   CqMpUScSnQV692X4e  192.168.33.10       1037  ...        11           8107        (empty)

[5 rows x 19 columns]
```

So a couple of questions/observations
- Is the conn.log really big (GigaBytes?) 
- If you're on an AWS instance those can sometimes have a small amount of RAM
- Can you send me a copy of the conn log? S3 bucket/URL link/etc..

Feel free to contact me directly at briford@supercowpowers.com

**Comment by jailenbailey** [comment]
Hi @brifordwylie,

I thank you for a timely response!

Being that this is the case, I think it confirms that there is likely something wrong with my environment (starting an internship with an issued laptop, I am sure I missed something or another in the environment setup). 

My conn.log file is only 36MB and is very standard with nothing outstanding or unique, and I am using a simple Windows 10 setup, running Notebooks in both Jupyter and VSCode. 

I will continue to attempt to figure out what the issue is. Since it is not a disconnect between versions, I am sure it is a really simple fix.

**Comment by jailenbailey** [comment]
Update:

I went super in the weeds to figure out exactly what was wrong here. It drove me absolutely insane because I couldn't find a single problem with my code, packages, environment, anything. 

It was so obvious. I was using LogToDataFrame on a JSON formatted log file **Facepalm**.

**Comment by brifordwylie** [comment]
Good to hear you worked it out... you've probably found it already but here's an example script that pulls in the JSON formatted log: https://github.com/SuperCowPowers/zat/blob/main/examples/zeek_json_to_pandas.py
