### ISSUE TITLE
Library issues -any suggestions

### ISSUE THREAD

**Issue by e101sg** [Kitware/bat#148]
Hi everyone, 
Glad to find the  ZAT tool -- very useful :) / Thanks to Superpower Cows!! 
New to Zeek and ZAT. Just to trying to execute the _anomaly_detection_streaming.py_ in examples folder. 
If not mistaken, this file able to read the Zeek log periodically  (say every 10 min) and try to find anomaly in that log. Right?
When i run this script, i getting error (AttributeError: 'LiveSimulator' object has no attribute 'readrows') as shown in the screen shot. 
Ubuntu 20.04 / Python 3.8.10.  Am i miss anythings? Any suggestions welcome. Thanks a lot.  

![Screenshot from 2023-01-09 17-24-02](https://user-images.githubusercontent.com/1925934/211276289-8c4885a2-b662-4d0f-9f38-9266f261b406.png)

Cheers!
Chandra

**Comment by brifordwylie** [comment]
@e101sg thanks for the bug report. Yes I think the example script is outdated...  the call on line 72 should just be
```
for row in reader.rows()
```
So I've changed the example and pushed the fix.. thank again for the bug report :) 

You should be able to do a new pull on the repo and try the example script again... you can also use the data included in the repo for a quick test (see below)

```
❯ python anomaly_detection_streaming.py ../data/dns.log
Opening Data File: ../data/dns.log
Opening Data File: ../data/dns.log
Successfully monitoring ../data/dns.log...
Successfully monitoring ../data/dns.log...
Changing column proto to category...
Changing column qtype_name to category...
Normalizing column Z...
Normalizing column query_length...
Normalizing column answer_length...
Normalizing column entropy...
Normalizing column id.resp_p...
```

**Comment by brifordwylie** [comment]
@e101sg have you had a chance to test the small fix? My tests are working... I'm going to close this ticket and if you're still having issues we can reopen.

**Comment by e101sg** [comment]
Dear Brian,
Greetings! Not yet. Will do on Friday (13th Jan). Will update in case of an
issue.
Thanks.

Warm Regards,
Chandra
