### ISSUE TITLE
Bug - Dataframe_to_Matrix.py file using deprecated Pandas method

### ISSUE THREAD

**Issue by welch-b** [Kitware/bat#150]
On line 109 in Dataframe_to_Matrix.py there is a deprecated Pandas method being used and needs to be updated. 

Ubuntu 22.04.3 LTS
I upgraded my Pandas to v2.0.3
On zat/zat/dataframe_to_matrix.py there is a deprecated method used on line 109. This is no longer a usable method as of Pandas 2.0.0. Running pytest on this file produces FAILED test. 

This bug notification comes from welchb@battelle.org through Battelle Memorial Institute. I am happy to fix this small bug :)

**Comment by brifordwylie** [comment]
Hiya, thanks a bunch for catching, this. Totally up to you if you want to submit a PR. I'll put you on the dev team so it's a bit easier.

**Comment by brifordwylie** [comment]
Okay.. I've merged in your PR and pushed a new pypi release (0.4.7)... thanks @welch-b

**Comment by welch-b** [comment]
Thanks for the quick turnaround Brian.


Ben Welch
Network Security Researcher
Cyber Trust and Analytics Division
***@***.***

Battelle
http://www.battelle.org<http://www.battelle.org/>
14401 Penrose Pl
Chantilly, VA 20151-1812
Connect with Battelle
Facebook<http://www.facebook.com/battelle> | LinkedIn<http://www.linkedin.com/company/battelle>
Twitter<http://www.twitter.com/Battelle> | YouTube<http://www.youtube.com/user/battelleinnovations>

This message is intended only for the use of the individual or entity to which it is addressed, and may contain information that is privileged, confidential and/or otherwise exempt from disclosure under applicable law. If the reader of this message is not the intended recipient or the employee or agent responsible for delivering the message to the intended recipient, any disclosure, dissemination, distribution, copying or other use of this communication or its substance is prohibited. If you have received this communication in error, please return to the sender and delete from your computer system.

________________________________
