### ISSUE TITLE
Whitelisting Example

### ISSUE THREAD

**Issue by swedishmike** [Kitware/bat#29]
Hi,

From the start - I'm not sure if this is a good idea or not. It might have consequences that I have not thought about. However, here it goes...

In my experience there are quite a few vendors that use DNS for various purposes. A/V vendors, like Sophos[1] for example, uses lookups for detection. These lookups tends to be quite weird looking and generates quite a lot of noise in DNS exfil rules and other such tools.

I had a look in the anomaly_detection.py script and sort of got an hamfisted piece of code together. It's not very elegant and definitely not very efficient. But at least it shows the idea to a certain extent. I put the 'maxmind.com' domain in there since that works on the provided example dns.log file and shows what I'm trying to achieve.

```
        # These domains could cause false positives, ie - long queries/responses, 
        # weird domain names etc.
        known_good = set(['sophosxl.net',  'maxmind.com']) 


        # Create a Pandas dataframe from a Bro log
        bro_df = log_to_dataframe.LogToDataFrame(args.bro_log)
        print('Read in {:d} Rows...'.format(len(bro_df)))

        # If the log type is dns and the known_good set is populated we will remove
        # rows if and when suitable/necessary.
        if log_type == 'dns' and len(known_good) > 0:
            print("Checking for 'known good' domains and will remove from the dataframe")
            for index, row in bro_df.iterrows():
                if any([domain in row['query'] for domain in known_good]):
                    # bro_df.drop(index, inplace=False)
                    bro_df.drop(index, inplace=True)
                else:
                    pass
            print("We now have {:d} Rows...".format(len(bro_df)))
        else:
            pass

```
1 - As stated, not sure if this is a good idea or not?

2 - I don't think I'm doing this in the most efficient way here - it seems to be quite an intensive operation in the way I'm doing it. I'll have a look at seeing if there's a better/more Pythonic way of doing it. Maybe there's a very established way of doing this that I just don't know about yet? Maybe it should even be done on the initial population of the dataframe somehow?

3 - I'm also aware that this could be done on the Bro side. Getting rid of these by using Bro scripting to never even log them would save both disk space and Splunk license costs and also resolve this issue. However, I think that being able to iterate through and 'whitelist' certain domains as you analyze your dns logs could be quite useful.

What's your thoughts on this?

Cheers, Mike

[1] 
1508220101.531867       CEypeHRT1TQrypVyk       192.1.1.1    57519   8.8.8.8 53      udp     21710   0.017866        3.1o19sr00or1942r9p3764opq8r30n2n4n91549o91253r94psn0o25s1o13r2p2.psqp3r741p635393648s22s52n1r1n0231997psrq7r530s1o70np98198np693.pn282s.rn3o9687n0r8o62pp317p94n645q2o618264op91.i.00.s.sophosxl.net       1       C_INTERNET      16      TXT     0       NOERROR F       F       T       T       0       TXT 3 x c       258.000000      F

**Comment by brifordwylie** [comment]
Hi @swedishmike,

I think having an example of removing whitelist items from a dataframe is good idea. I'll try to put together an example script in the next couple of days that's reasonably efficient.

**Comment by brifordwylie** [comment]
Done  https://github.com/SuperCowPowers/zat/blob/master/examples/pandas_whitelist.py
