### ISSUE TITLE
Change the way that the examples checks the name of the log files

### ISSUE THREAD

**Issue by swedishmike** [Kitware/bat#37]
Having played around with the example files I might have found a small issue.

The code currently roughly looks like this:

```
    if not args.bro_log.endswith('ssl.log'):
        print('This example only works with Bro ssl.log files..')
        sys.exit(1)
```
The potential issue here, as I see it, is the use of 'endswith'. 

Given the fact that when Bro rotates out the logfiles they get a name like 'ssl.21:00:00-22:00:00.log.gz' we'd end up not being able to open a file that had been extracted without manually renaming it.

Maybe we could do a 'endswith .log and contains ssl' or something along the lines of that.

Thoughts?

**Comment by brifordwylie** [comment]
@swedishmike good observation. I think your suggestion sounds good.  

#Random You probably already know about it but we have a zip/multi file reader bro_multi_log_reader.py so people can use that reader to read in the zipped rotated log files.

**Comment by swedishmike** [comment]
@brifordwylie Cheers - will start looking at this now that I got the initial PR for the new example in place.

**Comment by brifordwylie** [comment]
@swedishmike so in general the examples are meant to be 'looked at'.. meaning people should be running them and trying to understand the code. In this case the endwith logic is trying to be helpful but sometimes gets in the way. I like your suggestion of contains.. so I'll just pop that in.

**Comment by brifordwylie** [comment]
Closing with PR #65
