### ISSUE TITLE
New example to try and find Tor connections and also port number statistics

### ISSUE THREAD

**Issue by swedishmike** [Kitware/bat#38]
@brifordwylie 

I've just uploaded another branch called 'ssl_tor_and_port_count'. It adds two new files

- data/tor_ssl.log
- examples/tor_and_port_count.py

The example shows two more use cases for Bat.

1. Some people see Tor as something bad and wants to know if users are accessing Tor resources from their networks. One known way of doing this is to look for the issuer and subject of the certificates which follow a very special pattern. This script uses regex's to try and locate connections that follow this pattern and will report them.

2. Having encrypted traffic on unusual ports can be an indication of potentially malicious activity so this script also outputs the totals of the port numbers that Bro have identified SSL traffic on.

I've based this on one of the earlier examples so it will follow the 'normal standard' when it comes to positional argument for the log file and so on. It will also accept the '-t' argument to tail a live log file.

The total number of identified potential Tor connections and the port number statistics will currently only print if the program is not working on a live log file. This is something that I'm currently in two minds whether or not I should change so I print the stats intermittently on a live log file too. 

I've tested this back and forwards and it seems to work fairly ok. If you have the time could you please check out the branch and give it a go too and see if you can spot anything that's broken or something you'd want me to change?

If you're ok with me adding this to the main branch - please let me know and I'll make sure to sync the branch to the latest version and then create a pull request for a more formal review.

Cheers, Mike

P.S
I have not looked at adding anything to the Docs yet - I thought I'd run the program past you before I got into that bit. ;-)

**Comment by brifordwylie** [comment]
@swedishmike this example looks good. I've tested it out on my setup and seems to work fine, feel free to make a PR for it.

**Comment by swedishmike** [comment]
@brifordwylie Many thanks - added some further error handling and also initial steps towards the documenation. Will submit the PR now so please have a look.

**Comment by swedishmike** [comment]
PR approved so closing this issue now.
