### ISSUE TITLE
FEATURE REQUEST - Bro JSON

### ISSUE THREAD

**Issue by CyberTaoFlow** [Kitware/bat#40]
Greetings! Cool project and thank you for creating it and sharing it.

I opened the issue more as a feature request.  It would be nice if this also supported logs written by bro using the JSON output.  In some medium-large sensor deployments it is common to use JSON wherever possible to ease ETL and compatibility with things like the ELK stack etc.

**Comment by br0kej** [comment]
Hey Brian. Just spotted that this was recently re-opened. Is support for JSON log in dev?

**Comment by brifordwylie** [comment]
Hi @br0kej thanks for interest in the JSON log support... I'll definitely try to bump this issue up in priority, I'll keep this issue updated with progress.

**Comment by brifordwylie** [comment]
@br0kej okay.. so the JSON to dataframe is in with the merge of #119, there's an example of how to use it in:
- https://github.com/SuperCowPowers/zat/blob/master/examples/zeek_json_to_pandas.py

**Comment by br0kej** [comment]
> @br0kej okay.. so the JSON to dataframe is in with the merge of #119, there's an example of how to use it in:
> - https://github.com/SuperCowPowers/zat/blob/master/examples/zeek_json_to_pandas.py
> 

Awesome @brifordwylie!

**Comment by brifordwylie** [comment]
Also released a new Pypi version, so you should be able to `pip install --upgrade zat` and run the example above

**Comment by CyberTaoFlow** [comment]
Thank you for implementing this, no more conversion pipeline!
