### ISSUE TITLE
How to run anomaly_detection.py

### ISSUE THREAD

**Issue by DanielSpring** [Kitware/bat#42]
Hello Brian,

How do you run these py scripts? I tried looking on the handbook but it doesn't say. Also do custom written scripts have to be put in the $PREFIX/share/bro/site or a default folder (base), or do we put them in any folder thats suitable in what we are trying to log?

Kind regards
Daniel

**Comment by brifordwylie** [comment]
Hi @DanielSpring you run the scripts as a Python script

    $ python anomaly_detection.py <filepath>

Each script will provide help if you give the -h option

    $ python anomaly_detection.py -h

Let me know if you have additional questions...
