### ISSUE TITLE
Unable to open bro logs - [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by rohanbapat** [Kitware/bat#47]
Tried open conn.logs and dns.logs using BAT. 

When I try - 
`reader = bro_log_reader.BroLogReader('dns.log')`

I get an error  [Errno 22] Invalid argument

Traceback - 

  File "<ipython-input-20-8ebfb15ab80c>", line 52, in __init__
    'time': datetime.datetime.fromtimestamp(0), 'interval': datetime.timedelta(seconds=0),

Please help

**Comment by brifordwylie** [comment]
Hi @rohanbapat is this on a windows box? If so it might be related to #45 . If this is not under windows please give me additional information about your system, the version of python,  and the full traceback you get. :)

**Comment by rohanbapat** [comment]
Oh Im sorry. Yes it is related to #45 . I found out that the issue was because of some bug in Python 3.6 that renders datetime.datetime.fromtimestamp(0) invalid. Instead need to change that to datetime.datetime.fromtimestamp(86400) . Ref - https://bugs.python.org/issue29097

Thanks for responding!

**Comment by brifordwylie** [comment]
@rohanbapat awesome.. thanks for the link to https://bugs.python.org/issue29097 you have now solved #45 for us :)
