### ISSUE TITLE
Is there an issue with resampling/plotting of larger sets of data?

### ISSUE THREAD

**Issue by swedishmike** [Kitware/bat#55]
I've successfully done some resampling and plotting of data from various dns.log files from different hosts in my environment following the layout/example in https://github.com/Kitware/bat/blob/master/notebooks/Bro_to_Plot.ipynb.

Then I thought I'd do the same for conn.log and this is where I run into problems. I'm not sure if the issue lies with Bat and/or Pandas (or for that matter myself) so I thought I'd post it as an issue.

The steps I take are as follows:

```
bro_df = LogToDataFrame('data/conn.log')
bro_df.info()

<class 'bat.log_to_dataframe.LogToDataFrame'>
DatetimeIndex: 3596641 entries, 2018-01-03 08:59:43.217746 to 2018-01-03 09:54:49.948516
Data columns (total 20 columns):
conn_state        object
duration          timedelta64[ns]
history           object
id.orig_h         object
id.orig_p         int64
id.resp_h         object
id.resp_p         int64
local_orig        bool
local_resp        bool
missed_bytes      int64
orig_bytes        int64
orig_ip_bytes     int64
orig_pkts         int64
proto             object
resp_bytes        int64
resp_ip_bytes     int64
resp_pkts         int64
service           object
tunnel_parents    object
uid               object
dtypes: bool(2), int64(9), object(8), timedelta64[ns](1)
memory usage: 528.2+ MB

bro_df['uid'].resample('1T').count().plot()
plt.xlabel('Connections per Minute')
```

This gives the following output:

![image](https://user-images.githubusercontent.com/8100625/34560781-2828fb80-f13f-11e7-9bea-43458914b53d.png)

Which clearly looks incorrect.

I've tried using the rather small conn.log that's shipped in the /data directory for this repo and that works just fine which sort of leads me to think that it possibly could be related to the size of the dataframe?

I've also tried with different resample settings and none of them works.

The index seems to be sequential and doesn't contain any rogue entries. There are no duplicates either.

I've verified the same behavior on both Windows and Linux.

Any ideas?

**Comment by swedishmike** [comment]
Actually - I think I might have figured out what causes this.

After doing some df_bro.sort_index() and df_bro.head() I noticed that there are actually some really old stuff in there as well. Caused by the way that Bro logs connections when they are closed.

For example: 

![image](https://user-images.githubusercontent.com/8100625/34573959-df87b70c-f16d-11e7-8be3-ca29aa72ef5b.png)

This is taken from a logfile that was rotated out with the logged data between 09:00 and 10:00 on the 3rd of January. No wonder my plot looked weird.

Since this is how Bro works I guess I'd have to find a way of getting the name of the rotated file, run a sort_index, delete entries before that hourly window and then generate the plot. Or something.

@brifordwylie - Do you have any ideas on how to do this in a proper way? ;) Possibly take the last index entry, subtract an hour from that and remove anything that's earlier than that - using timedate?

**Comment by swedishmike** [comment]
Got sort of a fix for this issue now. I've based this on the need to plot from the log files that are rotated out every hour so the time range should be an hour. Should be easy to adapt for any time range though.

Quick and dirty code as an example:

```
bro_df = LogToDataFrame('data/conn.log')
bro_df.sort_index(inplace=True)  # Make sure to get the index in proper date order

# Sort out the first and last index entry as per your desired time range
last_entry = bro_df.index[-1:]
first_entry = last_entry - pd.Timedelta('1 hour')

# Finally we slice out the specified timerange and we can use that to plot
bro_df = bro_df[first_entry[0]: last_entry[0]]
```

@brifordwylie I was thinking that maybe I should add a quick note re this phenomenon in the Plot notebook ( https://github.com/Kitware/bat/blob/master/notebooks/Bro_to_Plot.ipynb ) what do you think?

**Comment by brifordwylie** [comment]
@swedishmike so I'm going through some of these old issues. Looking at the details of this one looks like it's a 'hey my data had some really old connection in them'. So as you observed not really a bat or Pandas issue here. I like your suggestion of maybe adding a 'filtering' example that shows the user how to get an hour of data from the dataframe. I'm going to close this issue and if you'd like to add some filtering examples to the notebooks that would be great. Or even better make a new notebook and have it show a bunch of different things you can do with a Pandas dataframe :)
