### ISSUE TITLE
Anomaly detection for entire bro log long period 

### ISSUE THREAD

**Issue by harispp** [Kitware/bat#56]
Hi I need to perform Anomaly detection detection for the entire bro log data continuously, I have found that **anomaly_detection_streaming.py** and **anomaly_detection.py** but no idea which one used for continuous monitor suppose for 1 month. Even if I used **anomaly_detection_streaming.py** when I restart the program it will start from current log only, the old data will miss. How I can turn the program for continuous monitor for long period of time without effecting the restart  of program.

**Comment by waxlamp** [comment]
Hi @harispp!

I generally handle this by reading in older, archived log files going back to the date I need to start from, filtering out data rows that are older than my target date, and using Python's `itertools` library to put together a stream of data from multiple files as needed.

It would be good to have this as a utility function within Bat. Let me know if this puts you on the right track, or if you need more detail.

**Comment by harispp** [comment]
Thanks for the feedback. 
I have few queries, actually I have to do this anomaly detection for long time with all past data. So instead of creating and generating models every time, is there any way to store the trained model  by adding each new data, and updating the model. And in-case the program exit load trained model from file.

**Comment by waxlamp** [comment]
Unfortunately I don't know how `sklearn` works, but maybe you can look into pickling the appropriate objects and function. Perhaps @brifordwylie can provide you some more specific help.

**Comment by harispp** [comment]
Thanks for the feedback.
