### ISSUE TITLE
Run from command line

### ISSUE THREAD

**Issue by Jouster500** [Kitware/bat#57]
I've been trying to get your package to work on the command line to get a feel for and understanding of how its doing its magic. Unfortunately, while python (both 2.7 and 3.6) does note success in importing and using the bat package, your basic example of `pprint` for the logs on the command line outputs nothing. Same goes for `print` which leads me to believe there is no working implementation for this to work on the command line.

The command of say `python3.6 test.py` which test.py is a direct copy of the brolog to python example on the docs, just hangs up doing nothing while running the command. Documentation isn't specific to working through command line, nor does it contain any information regarding why this isn't working. Any ideas?

**Comment by waxlamp** [comment]
Hi @Jouster500!

So, I just tried the example using Python 2.7 and a fresh checkout of the bat repository, and it worked for me. What's in the file you're using (`dhcp.log` in the example)? Was it generated by Bro?

**Comment by Jouster500** [comment]
@waxlamp As an example, here's the first 4 lines of the dhcp.log file that was part of the old 2012 competition using them...

`
{"ts":"2012-03-16T12:30:47.230000Z","uid":"CmIHTg3QMO3qO1pvj8","id.orig_h":"192.168.202.76","id.orig_p":68,"id.resp_h":"192.168.202.1","id.resp_p":67,"mac":"00:26:9e:83:a2:30","assigned_ip":"192.168.202.76","lease_time":0.0,"trans_id":2767872470} {"ts":"2012-03-16T12:31:57.740000Z","uid":"C7n9pQ2M87OAh8AvL1","id.orig_h":"192.168.204.69","id.orig_p":68,"id.resp_h":"192.168.204.1","id.resp_p":67,"mac":"00:26:b9:da:95:2c","assigned_ip":"192.168.204.69","lease_time":0.0,"trans_id":2023309577} {"ts":"2012-03-16T12:32:00.620000Z","uid":"CcB9Io1KfirIjTwH3l","id.orig_h":"192.168.202.102","id.orig_p":68,"id.resp_h":"192.168.202.1","id.resp_p":67,"mac":"f0:de:f1:2e:6a:5a","assigned_ip":"192.168.202.102","lease_time":0.0,"trans_id":7111068} {"ts":"2012-03-16T12:32:01.800000Z","uid":"CnHQJq18Z2U94Bbi2e","id.orig_h":"192.168.202.76","id.orig_p":68,"id.resp_h":"192.168.202.1","id.resp_p":67,"mac":"00:26:9e:83:a2:30","assigned_ip":"192.168.202.76","lease_time":0.0,"trans_id":4022009768}
`

...and continues like this for the remainder of the file. They were generated through bro, after processing the 2012 pcap to it.

**Comment by waxlamp** [comment]
Ah I see... I think maybe your input file has an older format -- bat expects input in "tabular" files in Bro's documented [log format](https://www.bro.org/sphinx-git/logs/index.html).

To get bat's basic example working, I expect you could write a short Python program to convert your JSON-based log file into a tab-separated file with header information as shown in the link above.

Let me know if you think this will work for you.

**Comment by swedishmike** [comment]
Also - don't forget that 'header lines' needs to be in there for Bat to properly parse the files. These are the files starting with #'s that are always put in at the top of every new logfile.

Example: 

#separator \x09
#set_separator  ,
#empty_field    (empty)
#unset_field    -
#path   conn
#open   2014-04-03-10-08-27
#fields ts      uid     id.orig_h       id.orig_p       id.resp_h       id.resp_p       proto   service duration        orig_bytes      resp_bytes      conn_state      local_orig      missed_byteshistory  orig_pkts       orig_ip_bytes   resp_pkts       resp_ip_bytes   tunnel_parents
#types  time    string  addr    port    addr    port    enum    string  interval        count   count   string  bool    count   string  count   count   count   count   table[string]

Cheers, Mike

**Comment by Jouster500** [comment]
Yeah it would seem the bro configurations i made removed that header. So when running the script on those headerless files, nothing got outputted. I tried it on a variation that did have it and all is well.

**Comment by swedishmike** [comment]
@Jouster500 - sweet! That has caught out quite a few people. ;)

If it's all good now - is it ok to close this issue?

**Comment by Jouster500** [comment]
Good to close.
