### ISSUE TITLE
ImportError: cannot import name 'df_stats'

### ISSUE THREAD

**Issue by rohankkathpal** [Kitware/bat#59]
Following function doesn't exist:
from bat.utils import df_stats
is there an alternative function available? cant find it in docs

**Comment by brifordwylie** [comment]
@rohankkathpal the risky domain notebook needs to be updated a bit (I'll make a ticket for that).. the df_stats did move. you can import it like this...
```
import bat.dataframe_stats as df_stats
```
Let me know if that works out okay.

**Comment by rohankkathpal** [comment]
Hi, it works, Thank you so much
