### ISSUE TITLE
bro_log_reader freezes for large files

### ISSUE THREAD

**Issue by bhklimk** [Kitware/bat#71]
Three significant issues with the bro_log_reader class:
1) For very large files (10^6 lines or greater) the readerrows() method is an inefficient way to create pandas dataframes.  
2) The bro_log_reader class also does not optimize numpy type based off the number of unique instances of bro log objects.  
3) Finally, the dict based approach in readerrows() puts the columns out of the expected order from the bro log

**Comment by brifordwylie** [comment]
Link to related issue: #23

**Comment by brifordwylie** [comment]
Closing this with the merge of #76
